apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ybhtg2m6c-python
  janus-idp.io/tekton: ybhtg2m6c-python
  backstage.io/kubernetes-id: ybhtg2m6c-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ybhtg2m6c-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
